name: Publish Client NPM Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish-client:
    runs-on: ubuntu-latest
    environment: flsurf-publish
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: Install npm dependencies in Flsurf/Client
        run: npm install
        working-directory: ./Flsurf/Client

      - name: Configure npm authentication
        run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
        working-directory: ./Flsurf/Client
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish npm package
        run: npm publish --access public
        working-directory: ./Flsurf/Client
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

